### ISSUE TITLE
Crash with last game version

### ISSUE THREAD

**Issue by yasha2008** [alza54/opensource2#7]

**Comment by asm00009** [comment]
its the triggerbot that crash when its gonna shoot right?

**Comment by asm00009** [comment]
its related to screen size ig. Its giving non sense numbers

**Comment by asm00009** [comment]
`__int64 sub_18005ADF0()
{
  return 0xFFFFFFFFi64;
}`
if i'm not wrong this is the function 49 of CEngineClient

**Comment by asm00009** [comment]
yeah GetScreenSize is now index 50 of CEngineClient

**Comment by alza54** [comment]
Yes it is. +1 each index. 

The fix for trigger bot will be released today.

**Comment by alza54** [comment]
https://github.com/alza54/opensource2/commit/7dbb3f4b7b34131da3f543726c3dd989307fff98

TriggerBot issue now has temporary workaround

**Comment by kWAYTV** [comment]
> [7dbb3f4](https://github.com/alza54/opensource2/commit/7dbb3f4b7b34131da3f543726c3dd989307fff98)
> 
> TriggerBot issue now has temporary workaround

Triggerbot shoots dropped weapons and when sniper rifle it's not scoped yet, watermark doesnt make sense for it to be inside of bunnyhop. Also how are you injecting the cheat? With EI manual mapping it's not fully working, i've to use thread hijacking.

**Comment by alza54** [comment]
@kWAYTV Thank you a lot! 

A) thanks for reporting the trigger bot issue, it’ll get fixed in a new release.

B) watermark is useful for determining is GlobalsVars/LevelInit signature outdated in a look (it’ll show -1 when GlobalsVars/LevelInit hook is outdated). 
You may remove it if you don’t like it. It’s in BunnyHop because it shows player’s velocity, which in future will be helpful for optimising legitimate hopping “downgrades”. 

C) new visuals, visual improvements coming in the next release. Key binds, custom colours, config files soon. 

D) to avoid negative impact on the game, using public injectors, common injection methods, not modifying source to make it work with Manual Map — will result in a VAC ban. You need to change hooking methods to make it work with the Manual Map method and you can go further. I personally play only against bots.

**Comment by kWAYTV** [comment]
> @kWAYTV Thank you a lot!
> 
> A) thanks for reporting the trigger bot issue, it’ll get fixed in a new release.
> 
> B) watermark is useful for determining is GlobalsVars/LevelInit signature outdated in a look (it’ll show -1 when GlobalsVars/LevelInit hook is outdated). You may remove it if you don’t like it. It’s in BunnyHop because it shows player’s velocity, which in future will be helpful for optimising legitimate hopping “downgrades”.
> 
> C) new visuals, visual improvements coming in the next release. Key binds, custom colours, config files soon.
> 
> D) to avoid negative impact on the game, using public injectors, common injection methods, not modifying source to make it work with Manual Map — will result in a VAC ban. You need to change hooking methods to make it work with the Manual Map method and you can go further. I personally play only against bots.

Thanks man excited to see the new updates and what you come up with and im gonna look into the manual map fix. I also dmed u in UC so we can contact as i imported an UI of mine to the cheat and maybe u like it.

**Comment by SYR2004** [comment]
no skin changer？

**Comment by kWAYTV** [comment]
> no skin changer？

ig he got tired of updating xd
